#!/bin/sh
set -eu
test -x /opt/matchmedia/matchmedia
test -f /opt/matchmedia/config/default.yaml
test -f /opt/matchmedia/public/index.html
test -f /opt/matchmedia/public/style.css
test -f /opt/matchmedia/public/app.js
echo "image ok"
